apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
        - name: mysite
          image: 778841258598.dkr.ecr.eu-west-2.amazonaws.com/mysite:81d7b66ad03f4c28a8535a2b0e8970698b8cc46b
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
