apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysite.fullname" . }}
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
  type: {{ .Values.app.service.type }}
