{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysite.fullname" . }}-grafana
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      protocol: TCP
  type: ClusterIP
{{- end }}
