{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysite.fullname" . }}-grafana-admin
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
{{- end }}
