{{- if .Values.kubeStateMetrics.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysite.fullname" . }}-kube-state-metrics
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kube-state-metrics
  template:
    metadata:
      labels:
        {{- include "mysite.labels" . | nindent 8 }}
        app.kubernetes.io/component: kube-state-metrics
    spec:
      serviceAccountName: {{ .Values.kubeStateMetrics.serviceAccountName }}
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.kubeStateMetrics.image.repository }}:{{ .Values.kubeStateMetrics.image.tag }}"
          imagePullPolicy: {{ .Values.kubeStateMetrics.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kubeStateMetrics.service.port }}
{{- end }}
