{{- if .Values.nodeExporter.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mysite.fullname" . }}-node-exporter
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "mysite.labels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
          args:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/host/root"
          ports:
            - containerPort: {{ .Values.nodeExporter.service.port }}
              hostPort: {{ .Values.nodeExporter.service.port }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host/root
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
{{- end }}
