{{- if .Values.nodeExporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysite.fullname" . }}-node-exporter
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: node-exporter
  ports:
    - port: {{ .Values.nodeExporter.service.port }}
      targetPort: {{ .Values.nodeExporter.service.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
