{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysite.fullname" . }}-prometheus
  labels:
    {{- include "mysite.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
      protocol: TCP
  type: ClusterIP
{{- end }}
